<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE beans[
        <!ELEMENT beans (bean*)>
        <!ELEMENT bean (property*)>
        <!ELEMENT property (#PCDATA)>

        <!ATTLIST bean id ID #REQUIRED>
        <!ATTLIST bean class CDATA #IMPLIED>
        <!ATTLIST property name CDATA #IMPLIED>
        <!ATTLIST property ref IDREF #IMPLIED>
]>


<beans>
    <bean id="userBasicDAO" class="com.example.qqzone.dao.impl.UserBasicDAOImpl"/>

    <bean id="topicDAO" class="com.example.qqzone.dao.impl.TopicDAOImpl"/>

    <bean id="userBasicService" class="com.example.qqzone.service.impl.UserBasicServiceImpl">
        <property name="userBasicDAO" ref="userBasicDAO"/>
    </bean>
    <bean id="topicService" class="com.example.qqzone.service.impl.TopicServiceImpl">
        <property name="topicDAO" ref="topicDAO"/>
        <property name="replyService" ref="replyService"/>
        <property name="userBasicService" ref="userBasicService"/>
    </bean>

    <bean id="user" class="com.example.qqzone.controller.UserController">
        <property name="userBasicService" ref="userBasicService"/>
        <property name="topicService" ref="topicService"/>
    </bean>
    <bean id="page" class="com.example.myssm.myspringmvc.PageController"/>
    <bean id="topic" class="com.example.qqzone.controller.TopicController">
        <property name="topicService" ref="topicService"/>
    </bean>
    <bean id="hostReplyDAO" class="com.example.qqzone.dao.impl.HostReplyDAOImpl"/>
    <bean id="hostReplyService" class="com.example.qqzone.service.impl.HostReplyServiceImpl">
        <property ref="hostReplyDAO" name="hostReplyDAO"/>
    </bean>
    <bean id="replyDAO" class="com.example.qqzone.dao.impl.ReplyDAOImpl"/>
    <bean id="replyService" class="com.example.qqzone.service.impl.ReplyServiceImpl">
        <property name="replyDAO" ref="replyDAO"/>
        <property name="hostReplyService" ref="hostReplyService"/>
        <property name="userBasicService" ref="userBasicService"/>
    </bean>
    <bean id="reply" class="com.example.qqzone.controller.ReplyController">
        <property ref="replyService" name="replyService"/>
    </bean>




</beans>